### POST request to user register
POST {{ host }}/api/users/register
Accept: application/json
Content-Type: application/json

{
    "username" : "athirat",
    "email" : "athiart@gmail.com",
    "firstname" : "Athirat",
    "lastname" : "Kaewwichien",
    "gender" : "MALE",
    "password" : "password",
    "confirm_password" : "password"
}

### POST request to user login
POST {{ host }}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email" : "athiart@gmail.com",
    "password" : "password"
}

