### GET request to /api/carts (Show carts customer)
GET {{ host }}/api/carts?customer_id=1
Accept: application/json
Content-Type: application/json


### POST request to /api/carts (Create Cart)
POST {{ host }}/api/carts
Accept: application/json
Content-Type: application/json

{
    "customer_id": 1,
    "product_id": 74,
    "amount": 2
}

###DELETE request to /api/carts/{cart} (Delete Cart)
DELETE {{ host }}/api/carts/20
Accept: application/json
