### GET request to /api/carts (Show carts customer)
GET {{ host }}/api/carts
Accept: application/json
Content-Type: application/json

{
    "customer_id": 2
}

### POST request to /api/carts (Create Cart)
POST {{ host }}/api/carts
Accept: application/json
Content-Type: application/json

{
    "customer_id": 2,
    "product_id": 3,
    "amount": 20
}

###DELETE request to /api/carts/{cart} (Delete Cart)
DELETE {{ host }}/api/carts/52
Accept: application/json
