### POST request to /api/orders (Create Order)
POST {{ host }}/api/customers/orders
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="customer_id"

31
------WebKitFormBoundary
Content-Disposition: form-data; name="address_customer_id"

1
------WebKitFormBoundary
Content-Disposition: form-data; name="image_receipt_path"; filename="img.png"
Content-Type: image/png

< ./img.png
------WebKitFormBoundary--

### GET request to /api/staffs/orders
GET {{ host }}/api/staffs/orders
Accept: application/json

### GET request to /api/customers/orders
GET {{ host }}/api/customers/orders/31
Accept: application/json

### GET request to /api/orders/{order}
GET {{ host }}/api/orders/1
Accept: application/json

### PATCH request to /api/orders/{order}
PATCH {{ host }}/api/orders/2
Accept: application/json
Content-Type: application/json

{
    "status": "PENDING"
}
