### GET request to /api/products (Show Products)
GET {{ host }}/api/products
Accept: application/json

###

### GET request to /api/products/{id} (Show Product)
GET {{ host }}/api/products/2
Accept: application/json

###

### GET request to /api/products/search (Search Products)
GET {{ host }}/api/products/search
Accept: application/json
Content-Type: application/json

{
    "query": "name product"
}
###

### POST request to /api/products (Create Product)
POST {{ host }}/api/products
Accept: application/json
Content-Type: multipart/form-data

{
    category_id=id
    brand_id=id
    name=name product
    description=description can null
    price=123
    stock=10
    rating=4.5
    accessibility=PRIVATE
    image_paths=@/path/to/your/image1.jpg
    image_paths=@/path/to/your/image2.jpg
}
###

### PUT request to /api/products/{id} (Update Product)
PUT {{ host }}/api/products/2
Accept: application/json
Content-Type: application/json

{
    "category_id" : 8,
    "brand_id" : 4,
    "name" : "name product1",
    "description" : "description can null",
    "price" : 123,
    "accessibility" : "PRIVATE"
}
###

### DELETE request to /api/products/{id} (Delete Product)
DELETE {{ host }}/api/products/20
Accept: application/json

###
